import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import Header from "../components/Header/Header";
import AuthProvider from "../components/AuthProvider/AuthProvider";


import { cn } from "@/lib/utils"
import Notifier from "@/components/Notifier/Notifier";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>
        <main>
          <AuthProvider>
            <Notifier/>
            <Header/>
            {children}
          </AuthProvider>
        </main>
      </body>
    </html>
  );
}
